# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest
steps:
  - checkout: self
    submodules: true
  - task: NodeTool@0
    inputs:
      versionSpec: '14.x'
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        ls 
        npm install -g yarn
        yarn install
        yarn run build
        ls
        pwd
  
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: 'dist'
      ArtifactName: 'sticks-frontend-drop'
      publishLocation: 'Container'